name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: install libraries
      shell: bash
      run: sudo apt install texlive-base texlive-xetex
    - name: Generates Resume
      run: xelatex resume.tex
    - name: Upload result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: resume
        path: resume.pdf

